# Generated by Django 3.0.4 on 2020-06-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='url',
            new_name='siteUrl',
        ),
    ]
