# Generated by Django 3.0.4 on 2020-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('scale', models.IntegerField()),
                ('ex_1_name', models.CharField(max_length=255)),
                ('ex_1_reps', models.CharField(max_length=255)),
                ('ex_1_sets', models.CharField(max_length=255)),
                ('ex_1_desc', models.TextField()),
                ('ex_2_name', models.CharField(max_length=255, null=True)),
                ('ex_2_reps', models.CharField(max_length=255, null=True)),
                ('ex_2_sets', models.CharField(max_length=255, null=True)),
                ('ex_2_desc', models.TextField(null=True)),
                ('ex_3_name', models.CharField(max_length=255, null=True)),
                ('ex_3_reps', models.CharField(max_length=255, null=True)),
                ('ex_3_sets', models.CharField(max_length=255, null=True)),
                ('ex_3_desc', models.TextField(null=True)),
            ],
        ),
    ]
