# Generated by Django 3.0.4 on 2020-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='ex_1_desc',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='ex_2_desc',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='ex_3_desc',
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_2_reps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_2_sets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_3_reps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_3_sets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
