# Generated by Django 3.0.4 on 2020-07-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200718_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='ex_1_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='ex_2_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='ex_3_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
