# Generated by Django 3.0.4 on 2020-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_workout_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='ex_1_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
