# Generated by Django 3.0.4 on 2020-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20200718_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='ex_1_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
