# Generated by Django 3.0.4 on 2020-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20200718_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='ex_1_desc',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_2_desc',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='ex_3_desc',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
