# Generated by Django 3.0.4 on 2020-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20200718_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='ex_1_desc',
            field=models.TextField(blank=True, default='', max_length=160),
        ),
    ]
